services:
  postgres:
    image: postgres:15
    container_name: telegram-postgres
    environment:
      POSTGRES_DB: telegram_db
      POSTGRES_USER: telegram_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - telegram-network

  backend:
    build: .
    container_name: telegram-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/telegram_db
      SPRING_DATASOURCE_USERNAME: telegram_user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - telegram-network

volumes:
  postgres_data:

networks:
  telegram-network:
    driver: bridge