server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: telegram-app

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

jwt:
  secret: mySuperSecretKeyForJWTGenerationInTelegramApp2024
  expiration: 86400000

logging:
  level:
    com.example.telegram: DEBUG
    org.springframework.security: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE